### PR TITLE
Update pybids to 0.7

### LINKED ISSUE #137: updating bids notebook to 0.7
@adelavega promised to help :)

### PR DESCRIPTION
**Pull request by adelavega**
Closes #137 

Let me know if I did the notebook stuff right.

Also, pybids has released, but I'm still waiting for my PR on nipype to be merged: https://github.com/nipy/nipype/pull/2737

Once that's merged and relased, we can bump the nipype version here and release this.

### CODE REVIEW

**Comment by miykael** [comment]
Hi @adelavega,
Thanks for the changes. I waited till https://github.com/nipy/nipype/pull/2737 was merged, which is now the case. But there are still some notebook errors (even though it tells that CircleCI passed). You can see it in https://circleci.com/gh/miykael/nipype_tutorial/673

The problem happens in this line: https://github.com/miykael/nipype_tutorial/pull/138/files#diff-c9494e725c39488e593e0306a9fb9d31L320

```
from nipype.interfaces.io import BIDSDataGrabber
from nipype.pipeline import Node, MapNode, Workflow
from nipype.interfaces.utility import Function

bg = Node(BIDSDataGrabber(), name='bids-grabber')
bg.inputs.base_dir = '/data/ds000114'

bg.inputs.subject = '01'
res = bg.run()
res.outputs
```

This creates the error `OSError: Output key: func returned no files`.
Do you know how to fix this?

**Comment by adelavega** [comment]
It seems that the Circle tests are passing to me now... Was it an issue of dependencies not being updated?

**Comment by adelavega** [comment]
Bump?

**Comment by miykael** [comment]
Thanks for the bump @adelavega - I apologize for the late reply. I didn't forget but was swamped with other work. The problem is, circleci seems to pass but when you look at the log of the "run tests 1" tab [here](https://circleci.com/gh/miykael/nipype_tutorial/678), you can see that `basic_data_input_bids.ipynb` crashes with:

```python
AttributeError: 'BIDSLayout' object has no attribute 'get_datatypes'
AttributeError: 'BIDSLayout' object has no attribute 'get_suffixes'
TypeError: __init__() got an unexpected keyword argument 'derivatives'
```

I also just saw that the pybids version wasn't updated in the Dockerfile. https://github.com/miykael/nipype_tutorial/pull/138/commits/f39141375ed4a879906252afd6679f0136f4e3c4 takes care of that. Let's see if that solves the issue.

**Comment by miykael** [comment]
The update of the `Dockerfile` did the trick. I will merge this after correcting a typo in the `generate.sh` file.

**Comment by adelavega** [comment]
Awesome @miykael! Thanks for taking the time.

**Pull request merged**
