### PR TITLE
fix/workaround for issues with new releases  of datalad, matplotlib, pybids/grabbit

### PR DESCRIPTION
**Pull request by djarecka**
- using temporary an older version of DataLad, see #49
- changing a `datalad` command in Dockerfile (it was failing to often, so Yarik suggested to try with and without parallelization) 
- fixing a new error with `BIDSLayout.get`
- using an old version of matplotlib ([error with the current version](https://circleci.com/gh/djarecka/nipype_tutorial/50?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) should be fixed)

### CODE REVIEW

**Comment by djarecka** [comment]
@miykael - I cancelled this build because some tests were failing anyway. I ran some shortest tests [here](https://circleci.com/gh/djarecka/nipype_tutorial/50?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) and it looks like there is an issue with matplotlib, it's also due to the newest release, with version 2.1.2 (most) tests work fine.

Unfortunately, when I used an older version of matplotlib, I got also problem with `basic_data_input_bids.ipynb`, you can se the error [here](https://circleci.com/gh/djarecka/nipype_tutorial/51?utm_campaign=build-failed&utm_medium=email&utm_source=notification).

Let me know if you know what to do with matplotlib (we can temporary use an older version, but probably we should check what to do with the current version) or with the bids notebook.

**Comment by djarecka** [comment]
@miykael - it looks like grabbits also decide to change something that breaks tutorial... I asked `pybids` team for suggestion (https://github.com/INCF/pybids/issues/142)

**Comment by djarecka** [comment]
@miykael - so I fixed the problem with `BIDSLayout.get`. I didn't have time to check what is wrong with new matplotlib (and probably won't have this week), so I asked for an older version, but we should find a fix for [this](https://circleci.com/gh/djarecka/nipype_tutorial/50?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

Hope, all test will pass now, but going to sleep...

**Comment by djarecka** [comment]
@miykael - I'll merge it, otherwise binder is not able to build a docker container. I'll create issues regarding the specific version of DataLad and matplotlib introduced in this PR

**Comment by miykael** [comment]
@djarecka, thank you for all the changes. So there's just the pybids part open or can this be closed?

**Comment by djarecka** [comment]
@miykael - Tal actually told be how to changed the syntax that it works, I'm using `layout.get` with the extra argument `return_type='file'`, see  [changes](https://github.com/djarecka/nipype_tutorial/commit/159d52b5d9a2bab94be02234ae40a2f5b5781e2d#diff-c9494e725c39488e593e0306a9fb9d31)

I opened issue regarding DataLad, for now I;m just using the previous version

**Pull request merged**
