### PR TITLE
Switches SPM version from dev to stable r7219

### PR DESCRIPTION
**Pull request by miykael**
As discussed here (https://github.com/kaczmarj/neurodocker/issues/228), I'm curious if it's not better if we switch to a stable SPM12 version in the tutorial. I'm worried that otherwise users will use the `dev` version for their scientific analysis. Which would be bad, as those versions might just disappear at one point.

What do others think?

### CODE REVIEW

**Comment by miykael** [comment]
The checks are not all passing. Not sure why it gives an "all green". But the last issue should have been taken care of with https://github.com/kaczmarj/neurodocker/issues/228.
Will send a commit with the update in a second.

**Comment by miykael** [comment]
It seems that this setup/environment doesn't work with `octave` (which we use in the [create interface](https://miykael.github.io/nipype_tutorial/notebooks/advanced_create_interfaces.html#Create-your-own-MATLAB-interface) section.

If you try to use `octave` you get the following error:
```
octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
/usr/bin/octave-cli: /opt/matlabmcr-2010a/v713/sys/os/glnxa64/libgcc_s.so.1: version `GCC_4.3.0' not found (required by /usr/lib/x86_64-linux-gnu/libgfortran.so.3)
```
The error can be found in [this circleci log ](https://circleci.com/gh/miykael/nipype_tutorial/458).

I assume that the version of `octave` doesn't work with the MATLAB_MCR version 2010a.

I therefore decided to close this PR again. The change from SPM12 version `dev` to `r7219` was just to prevent that users use `dev` for their scientific analysis. The functionality should otherwise be the same.

**Comment by miykael** [comment]
Thanks to @kaczmarj's help I was able to solve this issue. I just had to force `LD_LIBRARY_PATH` to take the `libgcc_s.so.1` from `/opt/miniconda-latest/envs/neuro/lib`.

**Comment by miykael** [comment]
The `advanced_create_interfaces.ipynb` notebook is passing. This is the only notebook that needs `octave`. Therefore the commit https://github.com/miykael/nipype_tutorial/pull/122/commits/0284f2164866b91557b467179d02acd8e3eb7d66 took care of the `libgcc_s.so.1` library issue.

I will merge this commit to master.

**Comment by miykael** [comment]
Not sure where to post this best, but switching SPM version from `dev` to `r7219` reduced the size of the docker image from 7.46GB to 5.29GB. This is due to the fact that MCR 2018B is 2.8GB and MCR version  2010a is only 520MB big.

@kaczmarj, this might be a "good to know" fact for you.

**Comment by kaczmarj** [comment]
thanks @miykael - this is great to know!

**Pull request merged**
