### PR TITLE
new dockerfile (contains #27)

### PR DESCRIPTION
**Pull request by djarecka**
Changing Dockerfile:
    - I removed ANTs and FreeSurfer, since there are not used
    - I included notebooks and data (partially because I wanted to use it with Binder)
    
* Updating index and some Intro-notebooks:
   - introducing Binder option (the link should be changed one the new Dockerfile is in the master and we build a new container with Binder)
   - providing link to my dockerhub image (can be changet to nipype_tutorial account)
   - providing a simpler option of running tutorial (without mounting directories)

* This PR contains also #27 

Problems:
I run `example- notebooks again and I'm having problem with plotting (2 last cells):
   - AttributeError: 'MaskedConstant' object has no attribute '_fill_value' for one of the plot_stat_map and one plot_glass_brain
Any chances you know this problem?

### CODE REVIEW

**Comment by miykael** [comment]
Wow, @djarecka ! Thanks for all the changes!

I kept ANTs and FreeSurfer to have it there for people how want to try it out. But you're right, kicking them out would make the docker image much more compact. But don't we need ANTs for the normalization example?

I'm happy to leave the link to your dockerhub image for nipype_tutorial.

I will look into the plotting problem with the 'exersice-*' notebooks.

Thank you again for all this.

**Comment by miykael** [comment]
@djarecka, I just saw that the updates of the new docker image are only in the `Dockerfile`. Could you also update [create_dockerfile.sh](https://github.com/miykael/nipype_tutorial/blob/master/create_dockerfile.sh)?

Like this I also know the according changes in neurodocker.

**Comment by djarecka** [comment]
@miykael 

sorry, I meant AFNI, not ANTs, it was late...
One reason for removing the software we're not using came from the installation notebook. There is a `nipype.test()` command that were failing without FreeSurfer license. I know we can include it as in `nipype` repo, but maybe it's just better to not run all tests. 
In general I'm trying to remove all errors from the notebooks, that's why all those weird `try/except`, so I can easier run entire notebook, and we can introduce a simple CI, I spend too much on manually testing tutorial with yet another Dockerfile ;-)

Yes, I was planning to include my bash script, just forgot. Will create a new PR.

**Comment by miykael** [comment]
@djarecka 

Ah, ok. You're right about AFNI, I sometimes use it for some cleaning of data, but for the moment we don't use it in the tutorial. So I think we should keep it out. FreeSurfer license can be bypassed with something like this: https://github.com/miykael/nipype_env/blob/master/level4/Dockerfile#L52

Thanks for all the `try/except` corrections. I have no expertise with CI, but I think there was a "run jupyter notebook" command, where you can surpress error messages?

Anyhow, I'm happy to make you collaborator of this repo, if you want? Like this you don't have to always wait for my ok to advance with your PRs. What do you think?

**Comment by djarecka** [comment]
@miykael 

I've never tried CI with notebooks, but I'm sure you can do it, was planning to read the post you added at #5.

Sure, I'm happy to be a collaborator. I'd still consult with you bigger changes and let you know if I'm planning to work on something specific. Merging notebooks is really painful, so would avoid working on the same notebooks at the same time.

**Comment by miykael** [comment]
Ah https://github.com/miykael/nipype_tutorial/issues/5, yes exactly something like this :-)

And you should now be collaborator and able to push PRs yourself. Yes, I will also discuss bigger changes with you, but just for in general. Being able to push to master yourself reduces headaches and overlapping code snippets.

**Pull request merged**
