### PR TITLE
Tests ci (closes #5)

### LINKED ISSUE #5: add tests for tutorials
we should connect this with circle ci, so that we can check that the tutorial works cleanly as docker containers are updated.

### PR DESCRIPTION
**Pull request by djarecka**
Adding tests and ci for notebooks (see #5):

- [x] adding script that converts and runs notebooks

- [x] adding circleCI

- [x] testing `basic*` and `introduction*` notebooks

- [ ] testing `example*` notebooks

- [ ] adding parallel runs to circleCI

- [ ] fixing docker layer caching (?)

### CODE REVIEW

**Comment by djarecka** [comment]
@miykael I added a test and circleCI file, but this works pretty well fo `basic*` notebooks and some `introduction*` (I don't run most of `introduction*` on purpose, since it mostly text and the one about jupyter would fail). 
Unfortunately have problems with `example_*` notebooks, I already extend time to 2h [here](https://github.com/miykael/nipype_tutorial/pull/39/files#diff-a6a88b4925c00fdd2e781a0510255b48R22), but I believe it shouldn't take so long...

**Comment by djarecka** [comment]
I was actually testing this on my account: https://github.com/djarecka/nipype_tutorial/pull/10 

I could't see how to add this repo to CircleCI, it's likely that it has to be you who adds the repo.

**Comment by miykael** [comment]
@djarecka thanks for all the work. I haven't used CircleCI yet, but always wanted to learn it. How can I help?

**Comment by miykael** [comment]
I added this project to my CircleCI account and it seems to be testing here: https://circleci.com/gh/miykael/nipype_tutorial/1

To run the tests locally, I should use ``pytest -v -s /home/neuro/nipype_tutorial/test_notebooks.py``, correct? Is there something else that I need to consider?

**Comment by djarecka** [comment]
@miykael - this was not fully finished, `example_*` were not working at the time when I took a break. But that's ok, I can submit a short PR that removes the `example_*` from tests for now and we can have a new PR where we can try to fix `example_` notebooks. 

Unfortunately, I can see that for some reason container built was failing due to the problem with dataset/datalad. I asked CircleCi to rebuild it and we will see.

**Comment by djarecka** [comment]
and yes, if you have all software installed the `pytest` command should work locally (I will remove later `-s`, this allowed me to see the print statements when I was testing)

**Comment by miykael** [comment]
Sorry that I already merged it. I didn't know if I can test it with CircleCI if it's not on master. But also, as it doesn't touch any other code, I thought that a partial merge would be ok.

Docker build seems to work with the second test.

**Comment by djarecka** [comment]
no worries, I think it's totally fine, especially that I'm not sure if I'll be able to work on it within next 2 weeks. Let me just clean it, so the tests are passing and will create another PR with the test that require more work.

**Pull request merged**
