### PR TITLE
Figures & other stylistic updates

### PR DESCRIPTION
**Pull request by miykael**
As discussed in https://github.com/miykael/nipype_tutorial/issues/55, I've added output figures and log files (except some of the very long workflow log streas) to `gh-pages` (https://github.com/miykael/nipype_tutorial/commit/ec7466021ab14c8876f82c9db4ad9c3d0749afa0).

While doing so, I've also updated the requested kernel version (set to `[default]`) and changed some stylistic things.

I've also switched the order of the "solution" and the "exercise/answer" cell, so that the `# write your solution here`" cell appears before the actual solution, just like [here](https://miykael.github.io/nipype_tutorial/notebooks/basic_data_input.html#Exercise-1).

### CODE REVIEW

**Comment by djarecka** [comment]
@miykael - do you want to test all notebooks with both pythons? I just decided to test only with python 3, since we're trying to move to py3, but we can probably start testing both.

I'm trying to rebuild the tests. I sometimes have also timeout. I believe didn't figure out which extra parameter should have to be changed to be safe.

**Comment by miykael** [comment]
@djarecka - testing all notebooks with both pythons would be a good idea, but that would mean we would need an additional conda environment in the docker image (i.e. creating another 1.8GB of volume), no?

How would you change the kernel in the notebook images? Replacing the specification at the end of the notebook might work.

**Comment by miykael** [comment]
I'm also for suggesting people to use py3. But I'm recommending to leave `default`. Because in the docker image, `default` is python3. If I'm not mistaken, it should be the `neuro` environment.

Now, we could also specify that it should use the `neuro` or an `py3` environment. But this would mean, anybody who opens the notebook locally on their machine (without docker), will get a kernel error, that `py3` or `neuro` wasn't found. This error shouldn't happen with `default`.

Therefore I propose to leave `default` in. But we could also rename `neuro` to `py3` to make it clear for user that they should use python 3. What do you think?

**Comment by djarecka** [comment]
Oh, I see what you mean. Sure, we can use `default` but I think that at the same time we can keep official docker images with py3 only, so we don't "create" a new Nipype users that use py2 instead of py3. Some people will want to use py2 anyway, but there are people that simple don't know which python they should choose when they're starting, so having a py3 as a default option might help in the future IMO.

don't have any opinion regarding env name

**Pull request merged**
