### PR TITLE
Moving user documentation from main homepage to nipype_tutorial - Pull Request

### PR DESCRIPTION
**Pull request by miykael**
This PR is a new attempt of moving the [user documentation](http://nipype.readthedocs.io/en/latest/users/index.html) from the main Nipype homepage, to the nipype_tutorial. Changes are based on what was discussed in https://github.com/miykael/nipype_tutorial/issues/37.

I went through all the documents in https://github.com/nipy/nipype/tree/master/doc/users and either integrated them in already existing notebooks or created new notebooks. To see the notebooks that were added or changed, see the two commits https://github.com/miykael/nipype_tutorial/commit/9f8a7b8383bf9eead49392483216365b2b5fd7f7 and https://github.com/miykael/nipype_tutorial/commit/91c372bc78e0c2bcedcc13e34184e818316afa54.

This PR will take care of issue https://github.com/miykael/nipype_tutorial/issues/3 and issue https://github.com/miykael/nipype_tutorial/issues/28

### CODE REVIEW

**Comment by miykael** [comment]
Conserning the three **WIP** notebooks:

**`nipype_cmd`**
Is the [`nipype_cmd`](http://nipype.readthedocs.io/en/latest/users/nipypecmd.html) documentation still relevant? I haven't used the `nipype_cmd` command yet, but it seems it needs the installation of nipype via `apt install python-nipype`. Will there not be a conflict if I first install nipype via conda/pip and than via `apt`?

**Saving Workflows and Nodes to a file (experimental)**
The example in the [Saving Workflows and Nodes to a file (experimental)](http://nipype.readthedocs.io/en/latest/users/saving_workflows.html) documentation, currently leads to two errors. As it is labeled as "experimental", shall I excluded it from the `nipype_tutorial`?

**Resource Scheduling and Profiling with Nipype**
Running an example of the [Resource Scheduling and Profiling with Nipype](http://nipype.readthedocs.io/en/latest/users/resource_sched_profiler.html) documentation currently leads to some errors. I will further investigate why it doesn't work.

**Comment by miykael** [comment]
Datalad issue seems to be solved, thanks to https://github.com/datalad/datalad/issues/2472#issuecomment-386889111.

**Comment by miykael** [comment]
@djarecka, @satra - this PR adds all Nipype [user docs](http://nipype.readthedocs.io/en/latest/users/index.html) from the main homepage. It would be ready to merge. Do you want to validate it?

The only open questions are the three WIP's mentioned in the [previous comment](https://github.com/miykael/nipype_tutorial/pull/77#issuecomment-385529548).

**Comment by satra** [comment]
`nipype_cmd` is now under `nipypecli` - i think there should be a section on `nipypecli`

@djarecka - can we write a test (in nipype) that checks for saving say the example workflows? also the example should be updated or fixed if it fails.

@miykael - the resource scheduling and profiling should work fine. perhaps the example needs to be updated. cpac, mriqc, fmriprep uses this extensively. @oesteban may be able to take a quick look.

**Comment by miykael** [comment]
The `nipypecli` section was added with [this notebook](https://github.com/miykael/nipype_tutorial/blob/2cf5af2fa60ba11675dfb763b1322beb405290e7/notebooks/advanced_command_line_interface.ipynb). It seems very short, as the [original page](http://nipype.readthedocs.io/en/latest/users/cli.html) was also very short. Perhaps we should extend the example with some use case.

About the examples, we currently have testing to make sure that all the notebooks pass. Do you mean tests to verify that the output created (i.e. niftis etc.) are correct?

The "resource scheduling and profiling" notebook was updated to the docker image, but the profiler seems to have an issue with the workflow structure nonetheless:
<details><summary>More info about the errors</summary>
If you run the workflow, you will get the following error:

```python
/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/utils/profiler.py in log_nodes_cb(node, status)
    142         'name': node.name,
    143         'id': node._id,
--> 144         'start': getattr(node.result.runtime, 'startTime'),
    145         'finish': getattr(node.result.runtime, 'endTime'),
    146         'duration': getattr(node.result.runtime, 'duration'),

AttributeError: 'list' object has no attribute 'startTime'
```

The problem is, that `node.result.runtime` is a list of `Bunch` and not just a `Bunch` variable. So, `node.result.runtime[0].startTime` would give me the desired start time.
</details>

If @oesteban knows a solution, that would already be great. But I will also look into the implementation of the profiler in cpac, fmriprep and mriqc.

**Comment by miykael** [comment]
Merging this issue, to have the new content on the website.

I will open a new issue to handle the three WIP notebooks about `nipypecli`, saving workflows and the "resource scheduling and profiling".

**Pull request merged**
