### PR TITLE
FIX default environment in notebooks

### LINKED ISSUE #115: Index.ipynb displays incorrectly in docker container
If you follow the instructions in the index container and load up the index.ipynb from that container, then the notebook doesn't display with the html hidden or the tables formatted correctly. Additionally, the links don't have the target set to "_blank" so clicking on them opens in the same tab. 

I think this is because the notebook opens with the `Python [default] ` kernel instead of `Python [conda env:neuro]`. I put together a quick PR switching the notebooks to have `Python [conda env:neuro]` as their default environment.

### PR DESCRIPTION
**Pull request by Shotgunosine**
closes #115

### CODE REVIEW

**Comment by Shotgunosine** [comment]
Circleci is choking on "miykael/nipype_tutorial:pull/118" as the tag for docker. Do you know why that would be?

**Comment by djarecka** [comment]
@Shotgunosine - I think CircleCI had some issue earlier today, but I tried to rerun and didn't help. Maybe will try again later. 

I'm actually surprised that you had the issue with opening notebooks. I'll double check it on my laptop

**Comment by miykael** [comment]
@djarecka, I also tried to rerun it. As you said this problem seems to solve itself sometimes.

I'm wondering if it's connected with the fact that the branch has `/` in the name. Perhaps this is an invalid version tag for docker?

**Comment by Shotgunosine** [comment]
@miykael looks that way:
"A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters."

from https://docs.docker.com/engine/reference/commandline/tag/

**Comment by miykael** [comment]
Ah, perfect! Thank you @Shotgunosine for checking that. Don't worry about those checks with your current changes. Worst case we will debug after merging them with master.

**Comment by miykael** [comment]
@Shotgunosine there was an update in `neurodocker` that installs SPM with MCR version 2018b, instead of 2018a. Could you therefore update your branch to master and rerun `generate.sh` with the newest neurodocker version?

**Comment by miykael** [comment]
@Shotgunosine - circleci throws a permission denied error (`sed: couldn't open temporary file /home/neuro/nipype_tutorial/sedbFwC0m: Permission denied
`).

Could you move the `sed` command just one line lower, just after `--user=root \`? Like this the whole command will be run as root and should take care of it.

**Comment by miykael** [comment]
Strange, this leads now only to errors during the testing. We need to elaborate if this is coming from the `sed` command or from something else.

**Comment by miykael** [comment]
The tests on circleci don't pass. I've tried to debug this locally and it turns out that everything is fine as long as the kernel is `Python [default]`, but that it crashes with `Python [conda env:neuro]`. This behaviour doesn't change if you `source activate neuro` before testing.

But the notebooks can be opened and executed if they are saved with the `Python [conda env:neuro]` kernel (as suggested in this PR).

Therefore, if we need to change the kernels, we probably need to add another section in the `test` scripts that resets the kernel to `default`. But I'm wondering, why do we need to change the kernel in the first place? Was it so that the entry point `index.ipynb` is directly opened in the executed form? If so, are we sure that this works? Perhaps there's a better approach for this?

**Comment by miykael** [comment]
This all is fine and help and makes it possible that circleci runs also for non-core contributors. I therefore will merge this. The current circleci error messages should be taken care of by https://github.com/miykael/nipype_tutorial/pull/130.

**Pull request merged**
