### PR TITLE
Nbval test

### PR DESCRIPTION
**Pull request by djarecka**
I decided to test nbval with pytest. I should read more, but the simplest usage works pretty well, I had to remove only a few cells from testing. 

@miykael  - what do you think?

### CODE REVIEW

**Comment by miykael** [comment]
@djarecka - It looks really cool! I love that you can see on CircleCI which cells are problematic.

I have two questions:
1. Which cells did you have to remove from testing and how did you do it? I don't see anything related to that in your commits.
2. How is it specified that the some of the cells are SKIPPED and not crashed?

**Comment by djarecka** [comment]
@miykael  -  check for `NBVAL_SKIP` in `introduction_jupyter-notebook`

**Comment by djarecka** [comment]
@miykael - my understanding that now we're not only checking if notebooks are running but also if they're giving "the same" output. I was actually surprised that it's working so well...

We can also switch to `--nbval-lax` that  only checking for the errors

**Comment by djarecka** [comment]
@miykael - good point. That why probably is working so well... So probably now we're doing more or less the same as running with `--nbval-lax`, but we didn't test anything more before.

Not sure, if it's important to the the output or not. Would have to leave output

**Comment by miykael** [comment]
I'm still confues against what the `--nbval` command controls, because with our "Clear Celled" notebooks, there's nothing to compare it to. Therefore, I would recommend to use `--nbval-lax`.

The only concern I have again is time. Before, testing time took about 2.5h, now it seems to take about 4.5h. Should we try with `--nbval-lax` and see if this reduces the overall testing time?

**Comment by djarecka** [comment]
yes, I'm guessing that `--nbval-lex` should be equivalent. And let's see, it could be also much faster.

**Comment by miykael** [comment]
Hmm... circleci timed out with `--nbal` and `--nbal-lax`. Under those circumstances I would recommend to stay (at least partially) with our previous testing environment. What do you think?

@djarecka - Do you think it makes sense to test the `examples` and `handson` with the previous testing and the others with `nbval`? `nbval` has a better error reporting and would therefore be more usefull.

**Comment by djarecka** [comment]
@miykael - yes, maybe we can try to run `reduce_notebook_load` before running the tests. I'm not sure if I understand why we have bigger problem with `--nbval-lax` than with `nbval`... I was expecting that this will be faster...

**Comment by miykael** [comment]
@djarecka - I'm on it :-) I've run many different versions to run `reduce_notebook_load` before the tests. And I think I have now one that works. Will submit a commit to your branch in just a bit.

I will also investigate the `--nbval-lax` and `nbval` issue. I don't understand it yet, neither.

**Comment by miykael** [comment]
@djarecka - Great, it seems to work nicely :+1: I really like it like this! It gives much more detailed about the tests.

In my opinion, this is ok for merging.

**Comment by miykael** [comment]
@djarecka - I love it like this. Will merge it directly.

Also, I just was able to create a parallel circleci version that reduces overall time velow 2h. Will create a pull request shortly.

**Pull request merged**
