### PR TITLE
Adds additional (non-nipype) software tutorials

### PR DESCRIPTION
**Pull request by miykael**
This PR would add additional neuroimaging and python tutorials, that are independent from Nipype:
- [nibabel](https://github.com/miykael/nipype_tutorial/blob/46dbaaa1056f6d8a9c7106c7c4ba4466bae2b4d6/notebooks/tutorial_nibabel.ipynb)
- [nilearn](https://github.com/miykael/nipype_tutorial/blob/46dbaaa1056f6d8a9c7106c7c4ba4466bae2b4d6/notebooks/tutorial_nilearn.ipynb)
- [numpy](https://github.com/miykael/nipype_tutorial/blob/46dbaaa1056f6d8a9c7106c7c4ba4466bae2b4d6/notebooks/tutorial_numpy.ipynb)
- [scipy](https://github.com/miykael/nipype_tutorial/blob/46dbaaa1056f6d8a9c7106c7c4ba4466bae2b4d6/notebooks/tutorial_scipy.ipynb)
- [pybids](https://github.com/miykael/nipype_tutorial/blob/46dbaaa1056f6d8a9c7106c7c4ba4466bae2b4d6/notebooks/tutorial_pybids.ipynb)

The notebooks are based on the notebooks from https://github.com/nipy/workshops/ and on the content from http://www.scipy-lectures.org/intro/index.html. I've adapted them a bit and already used them in my neuroimaging workshops.

@satra and @djarecka  -  what are your thoughts about including such non-nipype tutorials in the `nipype_tutorial`?

Also, I would have some other notebooks about [visualization with Python](https://github.com/miykael/workshops/blob/master/180309_marburg/notebooks/python/02_python_visualization.ipynb) and [statistics with Python](https://github.com/miykael/workshops/blob/master/180309_marburg/notebooks/python/06_python_statistics.ipynb), but I believe that they don't fit in the `nipype tutorial`. What do you think?

### CODE REVIEW

**Comment by miykael** [comment]
I've deleted the `pybids` tutorial, as it's content is already covered in [Data Input with BIDS](https://miykael.github.io/nipype_tutorial/notebooks/basic_data_input_bids.html).

**Comment by djarecka** [comment]
@miykael I'd personally add only tutorials that might help with this specific Nipype Tutorial (numpy etc.). But this is because in general I believe that if you give beginner too much "unrelated" content it's hard for them to filter what is really important to them (at least this was always my problem).  Of course, you can always make an effort to nicely describe the sections, so people are not confused.
And probably some people prefer one repo than 3 repos... 

But do you know about these [repos](https://github.com/neuro-data-science). With @satra we created  neuroML and neuroViz last summer.

**Comment by satra** [comment]
@miykael - i think some of it is fine.

there is a separate effort we have launched to be more general datascience: https://github.com/neuro-data-science/ and intended to be more extensive.

some of the things could go there as well.

**Comment by miykael** [comment]
@djarecka - you're right. Too many non related resources might be confusing. And I have to appologize, the nilearn and nibabel content is actually comming from https://github.com/neuro-data-science.

@satra and @djarecka - so would you prefer that I just link to https://github.com/neuro-data-science or should I include nilearn, nibabel, (and numpy and scipy?) in the nipype tutorial? I'm hesitating to introduce a new section "Non Nipype Tutorials" just for Nilearn and Nibabel.

**Comment by satra** [comment]
@miykael - linking to neuro-data-science sounds good, and @djarecka - we should update those tutorials to use a lighter docker container as well - perhaps during brainhack.

**Comment by djarecka** [comment]
@satra - yes, we should probably update it...
 
@miykael -  if you think that some of your notebooks should be added there, let us know or create a PR.

**Comment by miykael** [comment]
As discussed, this branch is not necessary and can therefore be deleted.

**Pull request closed without merging**
