### PR TITLE
adding the notebook used during ohbm18

### PR DESCRIPTION
**Pull request by djarecka**
I added a version of quickstart that I was using during OHBM18 hackathon. I started from `introduction_quicstart`, but changed most of the examples to be more neuroimaging oriented (using FSL).
@miykael - feel free to change the name etc., didn't want to remove the original quickstart notebook, so now there are two...

### CODE REVIEW

**Comment by djarecka** [comment]
@miykael what about we will leave both. Maybe I think more about our comfort to have useful teaching materials in one place, but I hope some beginner users might find it useful as well. Let me just slightly rename the tutorial  and be clear which is more neuro-oriented (will do it later today) and you'll see if this looks better.

**Comment by miykael** [comment]
@djarecka - Yes, you're right. Leaving both is the way to go.

**Comment by djarecka** [comment]
I've done some renaming and I'll just merge this, since @satra might be using for teaching.

**Comment by miykael** [comment]
@djarecka - Perfect! Thank you.

**Comment by satra** [comment]
@djarecka - the imaging quickstart tutorial currently does not cover `joinnode`. to maintain parity, all concepts should be covered.

**Comment by djarecka** [comment]
@satra - yes, I should add it. I knew that I'll not have time to show, but it should be included. created new issue

**Comment by djarecka** [comment]
@satra - are you teaching it this week?

**Comment by satra** [comment]
@djarecka - not teaching this week - taught last week but just noticed that joinnode was missing.

**Pull request merged**
