### PR TITLE
removing all outputs

### PR DESCRIPTION
**Pull request by djarecka**
I removed all outputs. I guess that was your suggestion from PR. I used to keep output so people could read the notebook even without running, but there are problems with new @satra image. When we try to run with jupyter notebook (not jupyter-lab) some notebooks can't be loaded.  

I removed output from all notebooks just in case, no other changes.

### CODE REVIEW

**Comment by miykael** [comment]
I think I encountered the same issue while running ``jupyter notebook``. Was the error something like the following?

```bash
[sprintf] expecting number but found string
```

About the outputs. I'm not sure if we should remove all outputs, I personally would just remove pipeline logs, if they are longer than 25-50 lines. Because I agree, keeping the output as here (https://miykael.github.io/nipype_tutorial/notebooks/basic_data_output.html#DataSink) is very useful. And when in doubt, I would rather leave the outputs than not.

Because of this I hesitate to merge your PR, what do you think?

**Comment by djarecka** [comment]
Yes, this is the error.

I like keeping output but I removed it yesterday, since I don't understand when this error can occur. I think not only long pipeline logs can lead to them. I honestly don't know what is the best solution that looked just as safest. 

Do you have any thoughts when the error occurs? with @satra we were testing the last `nhw17` image (it's huge, but it has data inside)

**Comment by satra** [comment]
if we clean outputs, run everything through notebook and save, we should be able to get it working with both lab and notebook.

we could also point to the nhw17 container - it doesn't contain all participants though only sub-01 and sub-02.

**Comment by djarecka** [comment]
@satra I can run it with notebook and home that the version will be compatible. 

I'm wondering if we should point to the new image in the @miykael repo, or you should add this during the workshop. If it contains only data for 2 subjects, some notebooks will not run.

**Comment by satra** [comment]
@djarecka - for tutorial purposes you can use neurodocker in reprozip mode to minimize the image just for the tutorial. you can also download the other subjects data prior to make the minimal container. you can also consider how to automate this process.

**Comment by miykael** [comment]
@djarecka, I have a rather powerful local machine and could run all notebooks within the ``nhw17`` image if you want? Otherwise, I'll leave it to you.

Concerning the tutorial notebooks. I think it makes sense to have the notebooks available under ``/repo``, just to be sure. But for certain courses, I would recommend people to use their own local copy, like this they can alter the notebooks and reuse their own version of them.

**Comment by djarecka** [comment]
@satra  - I personally liked the previous solutions, when repo and data were not necessarily part of the image, much better. I'm not sure what was the motivation behind changing the approach.
 I will leave to you and Michael to decide what should be the "official" approach.

@miykael if you really can do it quickly, that would be great. And I will remember for future to run everything with jupyter notebook and not jupyter lab.

**Comment by satra** [comment]
@djarecka, @miykael - docker allows overwriting any mount point, so anything can be made to mount to external locations. the intent of self-containing it was to provide the simplicity to the user to focus on the tutorials without having to worry about mounting and fetching data.

**Comment by miykael** [comment]
@satra, you're right. I will rewrite the `docker run...`` section to highlight that one can use either the image internal notebooks and data or the external ones.

@djarecka, I still get some errors when loading the notebooks, even without any output. Curiously, the error isn't always there. Sometimes the notebooks can be opened with no problem, other times not. I will try to solve that.

**Comment by djarecka** [comment]
@satra - yes, I see your point, I'm just worry that by removing this very basic issue (that could be very confusing at the beginning indeed), people will not know how to run their own code using the container. But I can change the docker part. 

I can also just add on top of the example from previous workshop that required mounting (I know you can mount to this image too, but I'm afraid that this can lead to even more problems when tried by beginners).

**Comment by djarecka** [comment]
@miykael - sorry I missed your answer before I replied. So I will leave the docker part to you.

Should I work on the error with other notebooks? Any specific one you're having problem with?

**Comment by satra** [comment]
@djarecka and @miykael - the nhw image is definitely overkill for nipype tutorial. so we should create a nipype tutorial image much like michael had before, but using neurodocker. temporarily it's ok to point to the nih workshop or nhw image (whenever this is finalized). we should also refine the tutorial to use ipyvolume for example to show inflated interactive images. (@miykael - the 3d notebook from neuroviz is fun)

**Comment by miykael** [comment]
@djarecka, the problem seems to occur almost always with ``basic_error_and_crashes.ipynb``. Would be great if you could find a solution to that.

@satra, all the notebooks under https://github.com/neuro-data-science are really cool. Wow, the 3D one is really cool. I will try to include this and perhaps others in the examples :+1: to explore the data.
Also, I created a smaller docker image for the tutorial, based on https://github.com/neurohackweek/jupyterhub-docker - see [create_dockerfile.sh](https://github.com/miykael/nipype_tutorial/blob/master/create_dockerfile.sh). I haven't created it yet but I hope it's a bit smaller.

**Comment by satra** [comment]
the only issue with afni from neurodebian is that it's really old. with fsl it will install 5.0.9 which is fine for the tutorial.

**Comment by satra** [comment]
you can also remove these three lines:
```
    --instruction "RUN bash -c \"curl -sSL  http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.0.0_1.0.2g-1ubuntu11.2_amd64.deb > libssl1.0.0_1.0.2g-1ubuntu11.2_amd64.deb && dpkg -i libssl1.0.0_1.0.2g-1ubuntu11.2_amd64.deb && rm libssl1.0.0_1.0.2g-1ubuntu11.2_amd64.deb\" " \
    --instruction "RUN bash -c \"curl -sSL http://download2.rstudio.org/rstudio-server-\$(curl https://s3.amazonaws.com/rstudio-server/current.ver)-amd64.deb >> rstudio-server-amd64.deb && dpkg -i rstudio-server-amd64.deb && rm rstudio-server-amd64.deb\" " \
    --instruction "RUN Rscript -e 'install.packages(c(\"neuRosim\", \"ggplot2\", \"fmri\", \"dplyr\", \"tidyr\", \"Lahman\", \"data.table\", \"readr\"), repos = \"http://cran.case.edu\")' " \
```

**Comment by satra** [comment]
i would suggest reducing it down to the essential libraries and packages. for example vtk and mayavi are not essentially, especially now that one can use ipyvolume :)

**Comment by djarecka** [comment]
@miykael - I don't have any problems with loading `basic_error_and_crashes.ipynb` (I guess I actually check all of them yesterday). I do have an error running but this is due to the path `/opt/tutorial`

**Comment by djarecka** [comment]
some notebooks give sometimes `Error: Can't make callback from given data`, but it's usually enough to close them and try to open again (not saying that this is perfect...)

**Comment by miykael** [comment]
@djarecka, the notebooks are now all up to date, and were run with the latest ``miykael/nipype_tutorial`` (but also works with ``satra/nih-workshop-2017`` - I tried ``satra/nhw17``, but wasn't able to download it).

@satra, I tried to make the docker image smaller, but haven't really succeeded, because as you said, I think it makes sense to have the latest AFNI and FSL version. Like this ``miykael/nipype_tutorial`` is complete enough so that it could also be used for other projects. An alternative option is to kick out every package that isn't essential for the tutorial and really trim the image, but I'm not sure if this is really useful.

Good luck with the neurohackweek! This year was unfortunately not possible, but I hope that I can join you next year.

**Comment by djarecka** [comment]
Thanks Michael! I will remember to make new changes in the jupyter-notebook!

**Comment by satra** [comment]
@miykael  - the image does not have a latest tag, so you have to use the specific call: `docker pull satra/nhw17:0.5` however, the repo inside it doesn't auto-update so if one uses it they will need to git pull the tutorial repo as well. 

regarding size, for tutorial purposes we should trim the size and then tell users that they could create a container with all the tools if they wanted to.

**Comment by miykael** [comment]
@satra, I was able to get the image size down to 9GB by only downloading sub-01 with datalad (without the freesurfer folder) and with installing FSL and AFNI via apt-get (see https://github.com/miykael/nipype_tutorial/commit/e80564e3103780c32916ba5296362256fe8a053f). I will rewrite the docker notebook to point out that miykael/nipype_tutorial is only for tutorial usage and that they should create their own container for their own usage. Is that ok for you, or should I install the newest AFNI version?

Also, even with output cleared out, I still get sometimes some errors when opening a notebook. I tried to figure out if any nbextension is responsible for that, but I wasn't yet able to pinpoint it down.

**Pull request merged**
