### PR TITLE
WIP: Try to run circleci jobs in parallel

### PR DESCRIPTION
**Pull request by miykael**
The idea of this PR is to run some of the tests on circleci in parallel. In particular, the basic and introduction notebooks can be run in parallel to the example scripts. And in the future we might have other example scripts that can be executed in parallel as well.

### CODE REVIEW

**Comment by miykael** [comment]
@djarecka - I tried to create a "workflow" on circleci to have some of the checks in paralle. Unfortunately it didn't work, because I don't know how to reuse the built docker image in the parallel jobs.

If by any chance you know how to solve this, cool. But don't waste your time on it. It's not crucial.

**Comment by djarecka** [comment]
@miykael - I don't know right now, but should learn how to do it properly. Will read other repos

**Comment by miykael** [comment]
I tried to figure it out, but it doesn't really work. I tried different caching versions, but nothing helped. So, from my perspective, we can close this PR again. But I will leave it open, if @djarecka wants to give it a try.

**Comment by miykael** [comment]
Closing this pull, as for the moment it's not relevant.

**Pull request closed without merging**
