### PR TITLE
updating gh-pages

### PR DESCRIPTION
**Pull request by djarecka**

### CODE REVIEW

**Comment by miykael** [comment]
@djarecka, this PR tells me it would add **+15,844** lines and delete **−122,987**, which seems a lot. I've checked how much it would be if I would update the pages and it said **+290** and **-87**.

Do you know why your numbers are so high? Can I help somehow?

**Comment by miykael** [comment]
Hmm.. I think part of it is the change from PNG files to SVG files for visualization. Which is ok for me.

**Comment by djarecka** [comment]
sorry, not sure why. maybe you can simply create a new gh-pages from a current master?

**Comment by djarecka** [comment]
sorry, not sure why. i used my old script, probably should update. maybe you can simply create a new gh-pages from a current master?

**Comment by djarecka** [comment]
sorry, not sure why. i used my old script, probably should update. maybe you can simply create a new gh-pages from a current master?

**Comment by miykael** [comment]
No problem, just did so with https://github.com/miykael/nipype_tutorial/commit/6d823176e9c9f4e9d9d4a780dcd68239f69346cb

**Pull request closed without merging**
