### PR TITLE
FIX: Do not use Circle's premium layer caching

### PR DESCRIPTION
**Pull request by oesteban**
Seems master is broken for that reason.

### CODE REVIEW

**Comment by djarecka** [comment]
@oesteban - circle ci required updates, but I'm pretty sure it doesn't solve the problem that some notebooks fail with new nipype

**Comment by oesteban** [comment]
Well, the first step was fixing the CI 👍

**Comment by oesteban** [comment]
Also, compared to old builds in master - it seems tests now go substantially slower. Could that be the cause?

**Comment by djarecka** [comment]
sure!
If you are interested, I can share with you what I found while testing it locally. 

here are also some older tests from circleci: https://github.com/djarecka/nipype_tutorial/compare/master...djarecka:effigies/test1.5?expand=1

**Comment by djarecka** [comment]
@oesteban - well, the test_3 get stuck

**Comment by djarecka** [comment]
@oesteban - I was chatting with @effigies about it, I can send you some smaller versions of notebooks - one that passes, the other that fails (get stuck)

**Comment by oesteban** [comment]
Okay, master is already broken - let's merge this one and at least we'll be able to compare. It also adds a nightly build, so we notice when things break earlier.

Let's try to find the problem through some other PR.

**Comment by djarecka** [comment]
@oesteban - I've send an email with examples, but just to update conversation here, I believe this is [the cell](https://github.com/miykael/nipype_tutorial/blob/master/notebooks/handson_preprocessing.ipynb?short_path=5f37b8e#L1591). And interestingly, when I remove the part “Masks and Probability maps” part it can work fine

**Comment by djarecka** [comment]
@oesteban - while you are at this, I was thinking that the way we handle `Dockerfile` is not the best, basically we have `generate.sh` bash script and `Dockerfile` in the repo. Should we remove `Dockerfile` and just generate it before running the test?

Having Dockerfile might be nice for the users, but we can add instruction how to create one

**Comment by oesteban** [comment]
> @oesteban - I've send an email with examples, but just to update conversation here, I believe this is [the cell](https://github.com/miykael/nipype_tutorial/blob/master/notebooks/handson_preprocessing.ipynb?short_path=5f37b8e#L1591). And interestingly, when I remove the part “Masks and Probability maps” part it can work fine

That could possibly be a memory issue. If we are hitting swap at points then it makes sense tests are, in general, suffering from a slow down.

We should try to pin nipype to the latest release after the previous successful build 8 months ago and see when we introduced the problem.

**Comment by oesteban** [comment]
> @oesteban - while you are at this, I was thinking that the way we handle `Dockerfile` is not the best, basically we have `generate.sh` bash script and `Dockerfile` in the repo. Should we remove `Dockerfile` and just generate it before running the test?
> 
> Having Dockerfile might be nice for the users, but we can add instruction how to create one

Sounds good, but for a different PR

**Comment by djarecka** [comment]
```
> That could possibly be a memory issue. If we are hitting swap at points then it makes sense tests are, in general, suffering from a slow down.

 I'm not sure how this could be a memory issue. The workflow shouldn't try to rerun at first place. The `test_3` is not just slower, it doesn't finish

you can try to run the notebooks I sent you

**Pull request merged**
